repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=5000"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.16.0
    hooks:
      # Run the linter and fix issues immediately when possible.
      # NOTE needs to run *before* the formatter and other tools like isort
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the Black-compatible formatter.
      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python)
